/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BookCondition = { 'new' : null } |
  { 'fair' : null } |
  { 'good' : null } |
  { 'poor' : null };
export type BookId = bigint;
export interface BookSummary {
  'id' : BookId,
  'title' : string,
  'ownerId' : Principal,
  'createdAt' : Time,
  'author' : string,
  'available' : boolean,
  'location' : string,
  'condition' : BookCondition,
}
export interface BookUpdateFields {
  'title' : [] | [string],
  'author' : [] | [string],
  'location' : [] | [string],
  'condition' : [] | [BookCondition],
}
export interface BorrowRequestSummary {
  'id' : RequestId,
  'status' : RequestStatus,
  'borrowerId' : Principal,
  'createdAt' : Time,
  'lenderId' : Principal,
  'bookId' : BookId,
}
export type RequestId = bigint;
export type RequestStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addBook' : ActorMethod<[string, string, BookCondition, string], BookSummary>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteBook' : ActorMethod<[BookId], boolean>,
  'getAIBookRecommendation' : ActorMethod<[string], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isMyOpenAIConfigured' : ActorMethod<[], boolean>,
  'isOpenAIConfigured' : ActorMethod<[], boolean>,
  'listAllBooks' : ActorMethod<[], Array<BookSummary>>,
  'listMyBooks' : ActorMethod<[], Array<BookSummary>>,
  'listMyReceivedRequests' : ActorMethod<[], Array<BorrowRequestSummary>>,
  'listMySentRequests' : ActorMethod<[], Array<BorrowRequestSummary>>,
  'respondToBorrowRequest' : ActorMethod<[RequestId, boolean], boolean>,
  'sendBorrowRequest' : ActorMethod<[BookId], [] | [BorrowRequestSummary]>,
  'setMyOpenAIApiKey' : ActorMethod<[string], undefined>,
  'updateBook' : ActorMethod<[BookId, BookUpdateFields], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];