/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BookCondition = IDL.Variant({
  'new' : IDL.Null,
  'fair' : IDL.Null,
  'good' : IDL.Null,
  'poor' : IDL.Null,
});
export const BookId = IDL.Nat;
export const Time = IDL.Int;
export const BookSummary = IDL.Record({
  'id' : BookId,
  'title' : IDL.Text,
  'ownerId' : IDL.Principal,
  'createdAt' : Time,
  'author' : IDL.Text,
  'available' : IDL.Bool,
  'location' : IDL.Text,
  'condition' : BookCondition,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RequestId = IDL.Nat;
export const RequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const BorrowRequestSummary = IDL.Record({
  'id' : RequestId,
  'status' : RequestStatus,
  'borrowerId' : IDL.Principal,
  'createdAt' : Time,
  'lenderId' : IDL.Principal,
  'bookId' : BookId,
});
export const BookUpdateFields = IDL.Record({
  'title' : IDL.Opt(IDL.Text),
  'author' : IDL.Opt(IDL.Text),
  'location' : IDL.Opt(IDL.Text),
  'condition' : IDL.Opt(BookCondition),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addBook' : IDL.Func(
      [IDL.Text, IDL.Text, BookCondition, IDL.Text],
      [BookSummary],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteBook' : IDL.Func([BookId], [IDL.Bool], []),
  'getAIBookRecommendation' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isMyOpenAIConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'isOpenAIConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllBooks' : IDL.Func([], [IDL.Vec(BookSummary)], ['query']),
  'listMyBooks' : IDL.Func([], [IDL.Vec(BookSummary)], ['query']),
  'listMyReceivedRequests' : IDL.Func(
      [],
      [IDL.Vec(BorrowRequestSummary)],
      ['query'],
    ),
  'listMySentRequests' : IDL.Func(
      [],
      [IDL.Vec(BorrowRequestSummary)],
      ['query'],
    ),
  'respondToBorrowRequest' : IDL.Func([RequestId, IDL.Bool], [IDL.Bool], []),
  'sendBorrowRequest' : IDL.Func([BookId], [IDL.Opt(BorrowRequestSummary)], []),
  'setMyOpenAIApiKey' : IDL.Func([IDL.Text], [], []),
  'updateBook' : IDL.Func([BookId, BookUpdateFields], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BookCondition = IDL.Variant({
    'new' : IDL.Null,
    'fair' : IDL.Null,
    'good' : IDL.Null,
    'poor' : IDL.Null,
  });
  const BookId = IDL.Nat;
  const Time = IDL.Int;
  const BookSummary = IDL.Record({
    'id' : BookId,
    'title' : IDL.Text,
    'ownerId' : IDL.Principal,
    'createdAt' : Time,
    'author' : IDL.Text,
    'available' : IDL.Bool,
    'location' : IDL.Text,
    'condition' : BookCondition,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RequestId = IDL.Nat;
  const RequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const BorrowRequestSummary = IDL.Record({
    'id' : RequestId,
    'status' : RequestStatus,
    'borrowerId' : IDL.Principal,
    'createdAt' : Time,
    'lenderId' : IDL.Principal,
    'bookId' : BookId,
  });
  const BookUpdateFields = IDL.Record({
    'title' : IDL.Opt(IDL.Text),
    'author' : IDL.Opt(IDL.Text),
    'location' : IDL.Opt(IDL.Text),
    'condition' : IDL.Opt(BookCondition),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addBook' : IDL.Func(
        [IDL.Text, IDL.Text, BookCondition, IDL.Text],
        [BookSummary],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteBook' : IDL.Func([BookId], [IDL.Bool], []),
    'getAIBookRecommendation' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isMyOpenAIConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'isOpenAIConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllBooks' : IDL.Func([], [IDL.Vec(BookSummary)], ['query']),
    'listMyBooks' : IDL.Func([], [IDL.Vec(BookSummary)], ['query']),
    'listMyReceivedRequests' : IDL.Func(
        [],
        [IDL.Vec(BorrowRequestSummary)],
        ['query'],
      ),
    'listMySentRequests' : IDL.Func(
        [],
        [IDL.Vec(BorrowRequestSummary)],
        ['query'],
      ),
    'respondToBorrowRequest' : IDL.Func([RequestId, IDL.Bool], [IDL.Bool], []),
    'sendBorrowRequest' : IDL.Func(
        [BookId],
        [IDL.Opt(BorrowRequestSummary)],
        [],
      ),
    'setMyOpenAIApiKey' : IDL.Func([IDL.Text], [], []),
    'updateBook' : IDL.Func([BookId, BookUpdateFields], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };