/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface BorrowRequestSummary {
    id: RequestId;
    status: RequestStatus;
    borrowerId: Principal;
    createdAt: Time;
    lenderId: Principal;
    bookId: BookId;
}
export interface BookUpdateFields {
    title?: string;
    author?: string;
    location?: string;
    condition?: BookCondition;
}
export interface BookSummary {
    id: BookId;
    title: string;
    ownerId: Principal;
    createdAt: Time;
    author: string;
    available: boolean;
    location: string;
    condition: BookCondition;
}
export type RequestId = bigint;
export type BookId = bigint;
export enum BookCondition {
    new_ = "new",
    fair = "fair",
    good = "good",
    poor = "poor"
}
export enum RequestStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    addBook(title: string, author: string, condition: BookCondition, location: string): Promise<BookSummary>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteBook(bookId: BookId): Promise<boolean>;
    getAIBookRecommendation(userPrompt: string): Promise<string>;
    getCallerUserRole(): Promise<UserRole>;
    isCallerAdmin(): Promise<boolean>;
    isMyOpenAIConfigured(): Promise<boolean>;
    isOpenAIConfigured(): Promise<boolean>;
    listAllBooks(): Promise<Array<BookSummary>>;
    listMyBooks(): Promise<Array<BookSummary>>;
    listMyReceivedRequests(): Promise<Array<BorrowRequestSummary>>;
    listMySentRequests(): Promise<Array<BorrowRequestSummary>>;
    respondToBorrowRequest(requestId: RequestId, approve: boolean): Promise<boolean>;
    sendBorrowRequest(bookId: BookId): Promise<BorrowRequestSummary | null>;
    setMyOpenAIApiKey(key: string): Promise<void>;
    updateBook(bookId: BookId, fields: BookUpdateFields): Promise<boolean>;
}
import type { BookCondition as _BookCondition, BookId as _BookId, BookSummary as _BookSummary, BookUpdateFields as _BookUpdateFields, BorrowRequestSummary as _BorrowRequestSummary, RequestId as _RequestId, RequestStatus as _RequestStatus, Time as _Time, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addBook(arg0: string, arg1: string, arg2: BookCondition, arg3: string): Promise<BookSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.addBook(arg0, arg1, to_candid_BookCondition_n1(this._uploadFile, this._downloadFile, arg2), arg3);
                return from_candid_BookSummary_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBook(arg0, arg1, to_candid_BookCondition_n1(this._uploadFile, this._downloadFile, arg2), arg3);
            return from_candid_BookSummary_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteBook(arg0: BookId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBook(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBook(arg0);
            return result;
        }
    }
    async getAIBookRecommendation(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getAIBookRecommendation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAIBookRecommendation(arg0);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isMyOpenAIConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isMyOpenAIConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isMyOpenAIConfigured();
            return result;
        }
    }
    async isOpenAIConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isOpenAIConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isOpenAIConfigured();
            return result;
        }
    }
    async listAllBooks(): Promise<Array<BookSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllBooks();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllBooks();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyBooks(): Promise<Array<BookSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyBooks();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyBooks();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyReceivedRequests(): Promise<Array<BorrowRequestSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyReceivedRequests();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyReceivedRequests();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMySentRequests(): Promise<Array<BorrowRequestSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMySentRequests();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMySentRequests();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async respondToBorrowRequest(arg0: RequestId, arg1: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.respondToBorrowRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.respondToBorrowRequest(arg0, arg1);
            return result;
        }
    }
    async sendBorrowRequest(arg0: BookId): Promise<BorrowRequestSummary | null> {
        if (this.processError) {
            try {
                const result = await this.actor.sendBorrowRequest(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendBorrowRequest(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async setMyOpenAIApiKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMyOpenAIApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMyOpenAIApiKey(arg0);
            return result;
        }
    }
    async updateBook(arg0: BookId, arg1: BookUpdateFields): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBook(arg0, to_candid_BookUpdateFields_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBook(arg0, to_candid_BookUpdateFields_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_BookCondition_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookCondition): BookCondition {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_BookSummary_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookSummary): BookSummary {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_BorrowRequestSummary_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BorrowRequestSummary): BorrowRequestSummary {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_RequestStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RequestStatus): RequestStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BorrowRequestSummary]): BorrowRequestSummary | null {
    return value.length === 0 ? null : from_candid_BorrowRequestSummary_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RequestId;
    status: _RequestStatus;
    borrowerId: Principal;
    createdAt: _Time;
    lenderId: Principal;
    bookId: _BookId;
}): {
    id: RequestId;
    status: RequestStatus;
    borrowerId: Principal;
    createdAt: Time;
    lenderId: Principal;
    bookId: BookId;
} {
    return {
        id: value.id,
        status: from_candid_RequestStatus_n15(_uploadFile, _downloadFile, value.status),
        borrowerId: value.borrowerId,
        createdAt: value.createdAt,
        lenderId: value.lenderId,
        bookId: value.bookId
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _BookId;
    title: string;
    ownerId: Principal;
    createdAt: _Time;
    author: string;
    available: boolean;
    location: string;
    condition: _BookCondition;
}): {
    id: BookId;
    title: string;
    ownerId: Principal;
    createdAt: Time;
    author: string;
    available: boolean;
    location: string;
    condition: BookCondition;
} {
    return {
        id: value.id,
        title: value.title,
        ownerId: value.ownerId,
        createdAt: value.createdAt,
        author: value.author,
        available: value.available,
        location: value.location,
        condition: from_candid_BookCondition_n5(_uploadFile, _downloadFile, value.condition)
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): RequestStatus {
    return "pending" in value ? RequestStatus.pending : "approved" in value ? RequestStatus.approved : "rejected" in value ? RequestStatus.rejected : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    fair: null;
} | {
    good: null;
} | {
    poor: null;
}): BookCondition {
    return "new" in value ? BookCondition.new : "fair" in value ? BookCondition.fair : "good" in value ? BookCondition.good : "poor" in value ? BookCondition.poor : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BookSummary>): Array<BookSummary> {
    return value.map((x)=>from_candid_BookSummary_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BorrowRequestSummary>): Array<BorrowRequestSummary> {
    return value.map((x)=>from_candid_BorrowRequestSummary_n13(_uploadFile, _downloadFile, x));
}
function to_candid_BookCondition_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookCondition): _BookCondition {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_BookUpdateFields_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookUpdateFields): _BookUpdateFields {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title?: string;
    author?: string;
    location?: string;
    condition?: BookCondition;
}): {
    title: [] | [string];
    author: [] | [string];
    location: [] | [string];
    condition: [] | [_BookCondition];
} {
    return {
        title: value.title ? candid_some(value.title) : candid_none(),
        author: value.author ? candid_some(value.author) : candid_none(),
        location: value.location ? candid_some(value.location) : candid_none(),
        condition: value.condition ? candid_some(to_candid_BookCondition_n1(_uploadFile, _downloadFile, value.condition)) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookCondition): {
    new: null;
} | {
    fair: null;
} | {
    good: null;
} | {
    poor: null;
} {
    return value == BookCondition.new ? {
        new_: null
    } : value == BookCondition.fair ? {
        fair: null
    } : value == BookCondition.good ? {
        good: null
    } : value == BookCondition.poor ? {
        poor: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
